CREATE DATABASE BDLOJA;
 
USE BDLOJA;
 
/*TABELA CATEGORIA*/
 
CREATE TABLE TBCATEGORIA (

IDCATE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

NOMECATE VARCHAR(25)

);
 
/*DADOS DA TABELA CATEGORIA*/

INSERT INTO TBCATEGORIA(NOMECATE)VALUES("INFANTIL"),("INFORMÁTICA"),("EDUCAÇÃO");
 
 
/*TABELA PRODUTOS*/

CREATE TABLE TBPRODUTO(

IDPROD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,

NOMEPROD VARCHAR(30),

PRECOPROD DECIMAL(7,2),

CODCATE INT NOT NULL,

FOREIGN KEY (CODCATE) REFERENCES TBCATEGORIA(IDCATE) ON DELETE CASCADE

)ENGINE=INNODB;
 
/*DADOS DA TABELA PRODUTO*/

INSERT INTO TBPRODUTO(NOMEPROD,PRECOPROD,CODCATE)

VALUES("Bola",120.00,1),

("Patinete",1500.00,1),

("Carrinho",15.00,1),

("Skate",300.00,1),

("Notebook",3000.00,2),

("Monito LG",1500.00,2),

("Teclado luzes",160.00,2),

("O Diário de Anne Frank",45.00,3),

("O dia do Curinga",65.00,3),

("O mundo de Sofia",48.00,3),

("Através do Espelho",38.00,3);
 
/*TABELA VENDA */

CREATE TABLE TBVENDA(
IDVENDA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DATAVENDA DATETIME,
FORMA VARCHAR(20)
);
 
/*DADOS DA TABELA VENDA*/

INSERT INTO TBVENDA(DATAVENDA,FORMA)
VALUES("2024/07/12","DINHEIRO"),
("2024/07/12","DÉBITO"),
("2024/07/13","CRÉDITO"),
("2024/07/13","PIX"),
("2024/07/13","DINHEIRO"),
("2024/07/15","CRÉDITO"),
("2024/07/15","DINHEIRO"),
("2024/07/15","PIX"),
("2024/07/16","PIX"),
("2024/07/16","PIX"),
("2024/07/18","DÉBITO"),
("2024/07/18","PIX");
 
/*TABELA ITENS DA VENDA */

CREATE TABLE TBITENS(
IDITEM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CODVENDA INT NOT NULL,
CODPROD INT NOT NULL,
QUANTIDADE INT,
FOREIGN KEY (CODVENDA) REFERENCES TBVENDA(IDVENDA) ON DELETE CASCADE,
FOREIGN KEY (CODPROD) REFERENCES TBPRODUTO(IDPROD) ON DELETE CASCADE
)ENGINE=INNODB;
 
/*DADOS DA TABELA ITENS DE VENDA */

INSERT INTO TBITENS(CODVENDA,CODPROD,QUANTIDADE)
VALUES(1,3,1),
(2,5,1),
(3,1,5),
(3,3,2),
(4,8,1),
(5,7,1),
(6,3,1),
(7,9,1),
(8,5,3),
(9,11,1),
(9,10,1),
(9,9,1),
(10,6,1),
(10,7,1),
(11,7,2),
(12,4,1);
 
/*Consultas*/
 
/*Exemplo 1- Exibição de quantidade de produtos por categoria*/

SELECT CODCATE, COUNT(*) AS "Total por categorias"

FROM tbproduto

GROUP BY CODCATE;
 
/*Exemplo 2- Exibir quantidade de formas de pagamento das vendas*/

SELECT FORMA, COUNT(*) AS "Quantidade de formas de pagamento nas vendas"

FROM tbvenda

GROUP BY FORMA;
 
/*Exemplo 3- Usando 2 tabelas*/

SELECT tbcategoria.NOMECATE,COUNT(*)

FROM tbcategoria, TBPRODUTO

WHERE tbcategoria.IDCATE=tbproduto.CODCATE

GROUP BY CODCATE;  
 
/*Exemplo 4- Usando apelidos para tabelas*/

SELECT V.IDVENDA, I.CODPROD, I.QUANTIDADE

FROM tbitens I, tbvenda V

WHERE I.CODVENDA=V.IDVENDA AND V.IDVENDA=3;
 
/*Exemplo 5- Usando 3 Tabelas*/

SELECT V.IDVENDA, P.NOMEPROD, I.QUANTIDADE

FROM tbitens I, tbvenda V, tbproduto P

WHERE I.CODVENDA=V.IDVENDA AND I.CODPROD=P.IDPROD 

AND V.IDVENDA=3;
 
/*Exemplo 6- Exibir a data da venda com o nome dos produtos e quantidade vendida da data de venda="2024/07/15"*/

SELECT V.DATAVENDA, N.NOMEPROD, I.QUANTIDADE

FROM tbvenda V, tbproduto N, tbitens I  

WHERE I.CODVENDA=V.IDVENDA AND I.CODPROD=N.IDPROD AND V.DATAVENDA="2024/07/15";
 
/*Exemplo 7 - Exibir o total de produtos de uma determinada venda específica*/
 
 
/*Exercicio 1*/

SELECT CODVENDA, NOMEPROD, QUANTIDADE 

FROM TBVENDA, TBITENS, TBPRODUTO

WHERE CODVENDA = IDVENDA AND CODPROD = IDPROD AND CODVENDA = 4;
 
/*Exercicio 2*/

SELECT NOMEPROD, PRECOPROD, NOMECATE

FROM TBCATEGORIA, TBPRODUTO

WHERE IDCATE = CODCATE;
 
/*Exercicio 3*/

SELECT DATAVENDA, IDVENDA, CODPROD, QUANTIDADE

FROM TBPRODUTO, TBVENDA, TBITENS

WHERE IDVENDA = CODVENDA AND CODPROD = IDPROD AND DATAVENDA = "2024/07/15"

GROUP BY IDVENDA;
 
/*Exercicio 4*/

SELECT FORMA, IDVENDA, QUANTIDADE AS "TOTAL DE ITENS DA COMPRA"

FROM TBVENDA, TBITENS

WHERE IDVENDA = CODVENDA AND IDVENDA = 6;
 
/*Exercicio 5*/

SELECT NOMECATE, NOMEPROD

FROM TBCATEGORIA, TBITENS, TBPRODUTO, TBVENDA

WHERE IDCATE = CODCATE AND IDPROD = CODPROD AND IDVENDA = CODVENDA AND IDVENDA = 9;
 
/*Exercicio 6*/

SELECT DATAVENDA, SUM(QUANTIDADE*PRECOPROD)

AS "TOTAL POR VENDA"

FROM TBITENS, TBPRODUTO, TBVENDA

WHERE CODPROD = IDPROD AND IDVENDA = CODVENDA AND DATAVENDA = "2024/07/13"

GROUP BY DATAVENDA;
 
/*JOIN*/
 
/*INNER JOIN*/

SELECT *

FROM tbproduto 

INNER JOIN tbitens

ON idprod = codprod;
 
/*LEFT JOIN*/

SELECT *

FROM tbproduto

LEFT JOIN tbitens

ON idprod = codprod;
 
/*RIGHT JOIN*/

SELECT *

FROM tbitens

RIGHT JOIN tbproduto

ON idprod = codprod;
 
/*EXEMPLO DELETE EM TABELA DEPENDENTE*/

/*VENDA 10 E 11 PRODUTO 7*/

DELETE

FROM tbitens

WHERE CODPROD = 7;
 
/*EXEMPLO DE DELETE QUE NAO FUNCIONA NA ESTRUTURA ATUAL*/

DELETE FROM TBCATEGORIA WHERE IDCATE = 1;
 
/*UPDATE EXEMPLO 1 - ALTERAÇÃO DE NOME PRODUTO*/

UPDATE tbproduto

SET NOMEPROD="BOLA DE BILHAR"

WHERE IDPROD=1;
 
/*UPDATE EXEMPLO 2 - ALTERAÇÃO DE QUANTIDADE DE PRODUTO DA VENDA*/

UPDATE TBITENS

SET QUANTIDADE=3

WHERE CODVENDA=3 AND CODPROD=1;
 
/*LISTA UPDATE E CIA*/

/*1*/

SELECT *

FROM TBVENDA

WHERE FORMA="DINHEIRO";
 
/*2*/

UPDATE TBVENDA

SET FORMA="À VISTA"

WHERE FORMA="DINHEIRO";
 
/*3*/

INSERT INTO TBCATEGORIA(NOMECATE)VALUES("DIABÓLICOS");
 
/*4*/

SELECT *

FROM TBPRODUTO

WHERE IDPROD=2;
 
/*5*/

UPDATE TBPRODUTO

SET NOMEPROD="ESPADA MALIGNA", PRECOPROD=10000.00, CODCATE=4

WHERE IDPROD=2;
 
/*6*/

SELECT *

FROM TBPRODUTO

WHERE CODCATE=4;
 
/*7*/

SELECT *

FROM TBITENS
 
/*8*/

SELECT P.NOMEPROD, P.PRECOPROD*I.QUANTIDADE AS "TOTAL POR PRODUTO"

FROM tbitens I, tbproduto P

WHERE I.codvenda=9 AND I.CODPROD = P.IDPROD;
 
/*9*/

UPDATE TBITENS

SET CODPROD=4, QUANTIDADE=2

WHERE CODVENDA=9 AND CODPROD=10;

/*10*/

SELECT P.NOMEPROD, I.QUANTIDADE

FROM tbitens I, tbproduto P

WHERE I.CODVENDA=9 AND P.IDPROD = CODPROD;
 
 